### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by samuelroeben** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-10#10]
**User Story**
As a user, I want to be able to create an account, so that I can access the app and my notes can be saved.

**Implementation**
Steps to implement the feature:
- [ ] Account create screen (username, email, password)
- [x] create function which creates the account

**Comment by myusome** [comment]
current state: only username is missing

**Comment by myusome** [comment]
`DataManager.signUp(email,password,name)` will create a new account, connect to a new session and add an empty template to the settings.
