### ISSUE TITLE
Calendar component

### ISSUE THREAD

**Issue by Brooke1803** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-10#18]
**User Story**
As a user, I want my calendar day components (#16) to be arranged to look like a calendar, because it's easier for me to find my notes this way.

**Implementation**
Steps to implement the feature:
- [x] Calendar month component that is a list of calendar days.
- [x] a possibility to navigate through the calendar component

**Comment by AlexW00** [comment]
Todo: fix bug where users cant navigate forward @samuelroeben @Brooke1803

**Comment by myusome** [comment]
bug issue will be made later
