### ISSUE TITLE
Generate prompt using GPT3

### ISSUE THREAD

**Issue by Brooke1803** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-10#19]
**User Story**
As a user, I want to get a personalized prompt for my generated editor input block (#7 ), so that I will get new inspiration for a greener life.

**Implementation**
Steps to implement the feature:
- [x] Alex: API route that returns a procedurally generated prompt based on the provided data using GPT3. (in Appwrite)
- [ ] My: change constructor for EditorModel: 4th BlockContent entry with GPT3 prompt as title

**Comment by myusome** [comment]
Problem: deployed function can not be executed succesfully on the appwrite server

Error:
```
An internal curl error has occurred within the executor! Error Msg: Could not resolve host: 62ebd3a59c321c79a842-6309f3f3f1f297736069
2022-08-27 12:36    failed    http    8.041s    
ErrorsOutput
2022-08-27 12:34    failed    http    8.462s    
ErrorsOutput
2022-08-27 12:28    failed    http    8.191s    
ErrorsOutput
 1 / 1 
GitHub
Discord
Open an Issue
Docs
v:0.15.3.402
```

**Comment by myusome** [comment]
function now deployed externally by @AlexW00 

```
GPT3-Title API:
- Url: https://gpt-title.deno.dev/
- Request typ: POST
- Body: { blockContents: blockContents }
```
(github: https://github.com/AlexW00/gpt-3-title-deno-function/blob/master/index.js)
