### ISSUE TITLE
Open Home Component on application start

### ISSUE THREAD

**Issue by AlexW00** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-10#27]
**User Story**
As a user, when I am logged in, and I start the web app, I want the #25 to show so that I can get started quickly.

**Implementation**
Steps to implement the feature:
- [ ] function (in DataManager), that returns the user's data #35 
- [ ] if the login failed show the login component instead
- [ ] if user has no template configuration setting load Template Configuration page #34
- [ ] function that return an Array of Dates, on which daily notes exist
- [ ] function that returns today's daily note (and creates an empty one if it does not already exist)

**Comment by myusome** [comment]
My: write function, that (actually) creates/logins user account
atm: automatic login into testuser account
